### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'NativeMagickImageCollection' threw an exception.

### ISSUE THREAD

**Issue by forest1102** [Noksa/WebDriver.Screenshots.Extensions#29]
First of all, thanks for making a great library, it helps a lot.  
However, when I upgraded version of .NET, TakeScreenShot start throwing an following error, if I run `dotnet publish`, and run the produced package. It runs perfectly with `dotnet run`.
I would appreciate very much if you can fix this problem quickly, or give me solution. 

```cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using OpenQA.Selenium;
using WDSE;
using WDSE.Decorators;
using WDSE.ScreenshotMaker;
namespace SeleniumScriptRunner
{
  public partial class ScriptGlobals
  {
    public static void TakeFullPageScreenshot(ref IWebDriver driver, string saveTo)
    {
      var scm = new ScreenshotMaker();
      scm.RemoveScrollBarsWhileShooting();
      var vcs = new VerticalCombineDecorator(scm);
      var bytesArr = driver.TakeScreenshot(vcs);
      File.WriteAllBytes(saveTo, bytesArr);
    }

  }
}
```

```
System.TypeInitializationException: The type initializer for 'NativeMagickImageCollection' threw an exception.
 ---> System.EntryPointNotFoundException: Unable to find an entry point named 'Environment_Initialize' in DLL 'Magick.NET-Q8-x64.Native.dll'.
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize()
   at ImageMagick.Environment.Initialize()
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection..cctor()
   --- End of inner exception stack trace ---
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection..ctor()
   at ImageMagick.MagickImageCollection..ctor()
   at WDSE.Decorators.VerticalCombineDecorator.CombineScreenshots(IWebDriver driver)  
   at WDSE.Decorators.VerticalCombineDecorator.MakeScreenshot(IWebDriver driver)      
   at WDSE.ExtensionMethods.TakeScreenshot(IWebDriver driver, IScreenshotStrategy strategy)
   at SeleniumScriptRunner.ScriptGlobals.TakeFullPageScreenshot(IWebDriver& driver, String saveTo) in 
   at Submission#0.<<Initialize>>b__0_1(IWebDriver driver)
   at SeleniumScriptRunner.ScriptGlobals.Test(String name, Action f) in 
```

## Versions

- Windows 10
- dotnet 6.0.100
- Nuget NuGet Version: 6.0.0.280

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>SeleniumScriptRunner</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="3.10.0"/>
    <PackageReference Include="Noksa.WebDriver.ScreenshotsExtensions" Version="0.1.5.4"/>
    <PackageReference Include="Selenium.Support" Version="4.1.0"/>
    <PackageReference Include="Selenium.WebDriver" Version="4.1.0"/>
    <PackageReference Include="CommandLineParser" Version="2.9.0-preview1"/>
    <PackageReference Include="System.Drawing.Common" Version="5.0.2"/>
    <PackageReference Include="Magick.NET-Q8-x64" Version="8.4.0"/>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="echo D | xcopy $(ProjectDir)contentFiles $(TargetDir)contentFiles  /I/E/Y
xcopy  $(ProjectDir)codes $(TargetDir)codes /I/E/Y"/>
  </Target>
  <Target Name="PostPublish" AfterTargets="AfterPublish">
    <Exec Command="xcopy $(ProjectDir)contentFiles $(PublishDir)contentFiles  /I/E/Y
xcopy  $(ProjectDir)codes $(PublishDir)codes /I/E/Y"/>
  </Target>
```

**Comment by forest1102** [comment]
Sorry. I fixed this issue by setting a specific runtime id on `dotnet publish`
